### ISSUE TITLE
[question] mindmap app

### ISSUE THREAD

**Issue by microcreators** [xmpf/mindmaps#1]
great start, but I'd add a couple of (hundred) points :)
any decent, not exactly $50/yr, mind mapping app? can be one off payment too.

**Comment by xmpf** [comment]
I will try to port this to FreeMind then.

**Comment by xmpf** [comment]
I will try to find alternatives that are compatible with XMind. Although, I also included the exported PDF so you should be fine.

**Comment by xmpf** [comment]
FreeMind, Freeplane, VUE are some open-source alternatives (listed in Wikipedia)
